server:
  port: 9527
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: gateway9527
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_rotes1
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/get/**
  application:
    name: cloud-gateway