server:
  port: 3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoT-guodong/springcloud-config
#          search-paths:
#            - config
#            - springcloud-config
      label: master
  application:
    name: config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"